/**
 * symbiote-workspace — Node-safe root entry point.
 *
 * Exports schema, validation, planning, sharing, and plugin utilities.
 * Does NOT import browser-only code (DOM, CustomElements).
 *
 * Browser-only assembly lives in `symbiote-workspace/browser`.
 * Server mode lives in `symbiote-workspace/server`.
 */

export {
  WORKSPACE_SCHEMA_VERSION,
  WORKSPACE_REGISTER_VALUES,
  DATA_BINDING_DIRECTIONS,
  WORKSPACE_CONFIG_SCHEMA,
  MODULE_CAPABILITY_SCHEMA_VERSION,
  MODULE_CAPABILITY_DESCRIPTOR_SCHEMA,
  validateModuleCapabilityDescriptor,
  validatePortableStringArray,
  validateWorkspaceConfig,
  isCompatibleVersion,
} from './schema/index.js';

export {
  loadWorkspaceConfig,
  extractThemeParams,
  extractThemeRelations,
  extractThemeOverrides,
  extractThemeSubtrees,
} from './loader/index.js';

export {
  planWorkspace,
  matchTemplate,
  listTemplates,
  getTemplate,
  normalizeConstructionIntent,
  buildConstructionQuestions,
  answerConstructionQuestion,
  planWorkspaceConstruction,
  extractConstructionPlan,
} from './constructor/index.js';

export {
  WORKSPACE_PACKAGE_KIND,
  WORKSPACE_PACKAGE_SCHEMA_VERSION,
  BROWSER_ENGINE_CONTRACTS_IMPORT,
  BROWSER_ENGINE_IMPORT,
  BROWSER_REQUIRED_IMPORTS,
  BROWSER_THEME_IMPORT,
  exportConfig,
  exportWorkspacePackage,
  importConfig,
  importWorkspacePackage,
  diffConfigs,
  mergeConfigs,
  createBrowserRuntimeContract,
  createHostIntegrationContract,
  createWorkspaceConstructionHandoff,
  createWorkspacePackageConstructionContext,
  createWorkspacePackagesConstructionContext,
  inspectWorkspacePackage,
  prepareConstructionIntentWithPackageContext,
  validateWorkspacePackage,
} from './sharing/index.js';

export {
  checkDesignGuardrails,
  loadWorkspaceDesignPolicy,
  normalizeWorkspacePatchReport,
  proposeWorkspacePatch,
  validateWorkspaceDesignPatch,
  validateWorkspacePatch,
  validateWorkspaceThemePatch,
  applyWorkspacePatch,
} from './validation/index.js';

export {
  assertCurrentCatalogProof,
  catalogProof,
  catalogSuggestions,
  catalogTools,
  createCatalog,
  createCatalogToolFamily,
  createConfigCatalogSource,
  createDevCatalogSource,
  createEngineCatalogSource,
  createRegistryCatalogSource,
  createStaticCatalogSource,
  validateCatalogProof,
} from './catalog/index.js';

export {
  PLUGIN_SCHEMA,
  validatePluginDefinition,
  validatePluginWorkspaceTemplate,
  registerPlugin,
  activatePlugin,
  unregisterPlugin,
  listPlugins,
  getPlugin,
  getPluginStatus,
  clearPlugins,
  validatePlugin,
  collectPluginModuleCapabilities,
  listPluginModuleCapabilities,
  collectPluginWorkspaceTemplates,
  listPluginWorkspaceTemplates,
} from './plugins/index.js';

export {
  dispatch,
  TOOLS,
  isMutating,
  createSession,
  buildToolResultEnvelope,
  parseToolResultEnvelope,
  isToolResultEnvelope,
  toolConfirmPolicy,
  isMutatingTool,
  needsConfirm,
  DATA_CHANGE_MESSAGE_TYPE,
  buildDataChangeMessage,
  isDataChangeMessage,
  broadcastDataChange,
  LESSON_CLAIM_KINDS,
  LESSON_CONTEXT_SCHEMA_VERSION,
  LESSON_RELATION_KINDS,
  LESSON_TEXT_RULES_VERSION,
  LESSON_TYPES,
  auditPresentationLessonContext,
  auditPresentationTimelineClaims,
  createPresentationLessonContext,
  lessonTextTokens,
  lessonToolIsSafeForDeepening,
  normalizeLessonToolDescriptor,
  validateLessonToolInput,
  PRESENTATION_COMPOSITION_ISSUE_CODES,
  PRESENTATION_COMPOSITION_PLAN_SCHEMA_VERSION,
  PRESENTATION_OUTPUT_SPEC_SCHEMA_VERSION,
  auditPresentationCompositionPlan,
  createLessonIntentHash,
  createPresentationCompositionPlan,
  normalizePresentationOutputSpec,
  normalizePresentationRect,
  normalizePresentationTargetComposition,
  presentationOutputOrientation,
  presentationRectsIntersect,
  PRESENTATION_PLANNER_INPUT_MAX_BYTES,
  PRESENTATION_PLANNER_INPUT_SCHEMA_VERSION,
  createPresentationPlannerInput,
  PRESENTATION_CONTRACT_VERSION,
  PRESENTATION_DIALOGUE_ACTS,
  PRESENTATION_CUE_KINDS,
  PRESENTATION_INTERACTION_TYPES,
  PRESENTATION_ANNOTATION_INTENTS,
  PRESENTATION_MARKERS,
  PRESENTATION_SYMBOLS,
  PRESENTATION_ANNOTATION_PLACEMENTS,
  PRESENTATION_STATE_CONDITIONS,
  PRESENTATION_SYNC_ANCHORS,
  PRESENTATION_DELIVERY_EMOTIONS,
  PRESENTATION_DELIVERY_PACES,
  PRESENTATION_DIALOGUE_ISSUE_CODES,
  PRESENTATION_DIALOGUE_QUALITY_PROFILE,
  PRESENTATION_DIALOGUE_QUALITY_PROFILE_VERSION,
  PRESENTATION_ALIGNED_SEQUENCE_VERSION,
  PRESENTATION_ALIGNMENT_RESOLUTIONS,
  PRESENTATION_CONTEXT_SNAPSHOT_SCHEMA_VERSION,
  PRESENTATION_LESSON_AUDIT_SCHEMA_VERSION,
  PRESENTATION_LESSON_REVIEW_CODES,
  PRESENTATION_PROMPT_PROFILES,
  PRESENTATION_REPLAN_REQUEST_SCHEMA_VERSION,
  PRESENTATION_REPLAN_RESULT_SCHEMA_VERSION,
  createPresentationAlignedSequence,
  createPresentationContextSnapshot,
  createPresentationLessonAuditPacket,
  createPresentationReplanRequest,
  createPresentationTimelineContract,
  createPresentationTimelineHash,
  createPresentationTtsProjection,
  createWorkspacePresentationTimeline,
  finalizePresentationReplan,
  normalizePresentationPrompt,
  normalizePresentationTimeline,
  normalizePresentationCue,
  normalizePresentationSyncAnchor,
  presentationTimelineHashProjection,
  presentationTimelineHasTurns,
  validatePresentationAlignedSequence,
  reviewPresentationTimeline,
  reviewPresentationDialogue,
  reviewPresentationTimelineAgainstLessonContext,
  reviewPresentationTimelineAgainstSnapshot,
  summarizePresentationTimeline,
  MEDIA_PROJECT_DEFAULT_SURFACE,
  MEDIA_PROJECT_ROUTE_JOB_PARAM,
  MEDIA_PROJECT_ROUTE_PREVIEW_FRAME_PARAM,
  MEDIA_PROJECT_ROUTE_PREVIEW_MODE_PARAM,
  MEDIA_PROJECT_ROUTE_REATTACH_PARAM,
  MEDIA_PROJECT_ROUTE_PARAM,
  MEDIA_PROJECT_ROUTE_SOURCE_URL_PARAM,
  MEDIA_PROJECT_ROUTE_SOURCE_SURFACE_PARAM,
  MEDIA_PROJECT_ROUTE_SOURCE_TAB_PARAM,
  MEDIA_PROJECT_ROUTE_WORKSPACE_SECTION_PARAM,
  MEDIA_PROJECT_ROUTE_TIMELINE_CURSOR_PARAM,
  MEDIA_PROJECT_ROUTE_TIMELINE_PARAM,
  MEDIA_PROJECT_SCHEMA_VERSION,
  AUDIO_SYNTHESIS_RECEIPT_VERSION,
  MEDIA_ARTIFACT_GRAPH_SCHEMA_VERSION,
  MEDIA_ARTIFACT_KINDS,
  MEDIA_ARTIFACT_VERSION_INPUTS,
  MEDIA_EVIDENCE_MANIFEST_SCHEMA_VERSION,
  MEDIA_SPEAKER_IDENTITY_CLAIMS,
  MEDIA_RENDER_DIRTY_SCOPES,
  MEDIA_RENDER_EVENT_SCHEMA_VERSION,
  MEDIA_RENDER_EVENT_TYPES,
  MEDIA_RENDER_READINESS_SCHEMA_VERSION,
  MEDIA_RENDER_SETTINGS_SCHEMA_VERSION,
  applyMediaRenderEvent,
  createMediaProject,
  createMediaProjectId,
  createMediaProjectRouteSearch,
  createMediaRenderEvent,
  createMediaArtifactCacheKey,
  createMediaArtifactGraph,
  createMediaEvidenceManifest,
  createMediaSynthesisEvidence,
  createMemoryMediaProjectStore,
  createStorageMediaProjectStore,
  invalidateMediaProjectArtifacts,
  invalidateMediaArtifactGraph,
  isMediaRenderEventType,
  mapRenderJobEventToMediaRenderEvents,
  mapRenderJobStageToMediaRenderEventType,
  normalizeMediaProject,
  normalizeMediaRenderEvent,
  normalizeMediaRenderReadiness,
  normalizeMediaRenderRouteState,
  normalizeMediaRenderSettings,
  parseMediaProjectRouteSearch,
  selectMediaProjectTimeline,
  updateMediaProjectRenderSettings,
  validateMediaArtifactGraph,
  validateMediaEvidenceManifest,
  validateMediaSynthesisEvidence,
  VIRTUAL_SEQUENCE_EXECUTION_TIERS,
  VIRTUAL_SEQUENCE_INVALIDATION_MODES,
  VIRTUAL_SEQUENCE_LAYER_KINDS,
  VIRTUAL_SEQUENCE_SCHEMA_VERSION,
  createVirtualSequence,
  invalidateVirtualSequence,
  projectVirtualSequenceAt,
  validateVirtualSequence,
} from './runtime/index.js';
